export const ADD_INGREDIENT_BURGER_CONSTRUCTOR = 'ADD_INGREDIENT_BURGER_CONSTRUCTOR';
export const DELETE_INGREDIENT_BURGER_CONSTRUCTOR = 'DELETE_INGREDIENT_BURGER_CONSTRUCTOR';
export const SWAP_INGREDIENTS = 'SWAP_INGREDIENTS';